name: Build & deploy
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

      # Allows to trigger the workflow from GitHub interfaces.
    workflow_dispatch:

# A single workflow can have multiple jobs.
jobs:
  # 'A new job is defined with the name: "build_android"
  build_android:
    # Defines what operating system will be used for the actions.
    # For android, we will use Linux GitHub-Hosted Runner.
    runs-on: ubuntu-22.04
    # Defines what step should be passed for successful run
    steps:
      # Checkout to the selected branch
      - name: Checkout
        uses: actions/checkout@v3
      # Download and install flutter packages
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          # Define which stable flutter version should be used
          flutter-version: "3.7.0"
          channel: 'stable'
          # Enables cache for flutter packages
          # Speed up the process
          cache: true
      # Get Flutter project dependencies
      - name: Get dependencies
        run: flutter pub get

      - name: Build release app bundle
        run: flutter build appbundle

      # Sign app bundle with keystore data
      - name: Sign App Bundle
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: build/app/outputs/bundle/release/
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE_BASE64 }}
          alias: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEYSTORE_KEY_PASSWORD }}

      - name: Upload to Play Store (Internal Testing)
        uses: r0adkll/upload-google-play@v1.0.18
        with:
          serviceAccountJsonPlainText: ${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON }}
          packageName: eg.edu.miuegypt.booksnbox
          releaseFiles: ${{steps.sign_app.outputs.signedReleaseFile}}
          mappingFile: ./build/app/outputs/mapping/release/mapping.txt
          track: internal