name: Android CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      - name: Build Android AAB
        run: flutter build appbundle --release

      - name: Set up Google Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '343.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Google Play
        env:
          APPLICATION_ID: 'your.application.id'  # Replace with your app's package name
        run: |
          gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
          gcloud config set project your-project-id  # Replace with your actual Google Cloud project ID
          gcloud alpha app bundles upload ./build/app/outputs/bundle/release/app-release.aab --account=$GOOGLE_CLOUD_EMAIL --no-gzip
          gcloud beta app distribution releases upload --track=internal --app=$APPLICATION_ID --bundle=./build/app/outputs/bundle/release/app-release.aab