name: Flutter CI/CD

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android AAB
        run: flutter build appbundle --release

      - name: Sign Android AAB
        run: |
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
            -keystore ${{ secrets.KEYSTORE_FILE }} \
            -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} \
            ./build/app/outputs/bundle/release/app-release.aab \
            ${{ secrets.KEY_ALIAS }}

      - name: Verify Android AAB signature
        run: jarsigner -verify -verbose -certs ./build/app/outputs/bundle/release/app-release.aab

      - name: Deploy to Google Play
        uses: wzieba/Google-Play-Deploy-Github-Action@v1
        with:
          service_account_json_key: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}
          package_name: eg.edu.miuegypt.booksnbox
          aab_path: ./build/app/outputs/bundle/release/app-release.aab